[package]
name = "grimoire"
version = "0.1.0"
edition = "2021"
authors = ["aemogie."]
description = "a spellcaster's content-addressable storage"

[[example]]
name = "imnewtorust"

[dependencies]
digest = "0.10.7"

[dev-dependencies]
sha2 = "0.10.8"
