[package]
name = "grove"
version = "0.1.0"
edition = "2021"
authors = ["aemogie."]
description = "a magical content-addressable filesystem"

[[example]]
name = "imnewtorust"

[dependencies]
digest = "0.10.7"

[dev-dependencies]
sha2 = "0.10.8"
